apiVersion: networking.k8s.io/v1beta1			
kind: Ingress				
metadata:
  name: board			
  annotations:
    nginx.ingress.kubernetes.io/app-root: /swagger-ui.html
    ingress.kubernetes.io/ssl-redirect: "false"
    
spec:
  rules:
  - host: api.board.com
    http:
      paths: 
      - path: /api/v1
        backend:
          serviceName: board-loadbalancer
          servicePort: 8761
  - host: swagger.board.com
    http:
      paths: 
      - path: /swagger
        backend:
          serviceName: board-loadbalancer
          servicePort: 8761
      - path: /webjars
        backend:
          serviceName: board-loadbalancer
          servicePort: 8761
      - path: /v2
        backend:
          serviceName: board-loadbalancer
          servicePort: 8761
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: board-dp
spec:
  replicas: 2
  selector:
    matchLabels:
      type: app
      service: board
  template:
    metadata:
      labels:
        type: app
        service: board
    spec:
      containers:
      - name: board
        image: huijun.azurecr.io/board:v1
---
apiVersion: v1
kind: Service
metadata:
  name: board-loadbalancer
spec:
  type: LoadBalancer
  ports: 
  - port: 8761
    protocol: TCP
    targetPort: 8080
  selector:
    type: app
    service: board