apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-dp
  namespace: production	
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: board
  template:
    metadata:
      labels:
        type: app
        service: board
    spec:
      containers:
      - name: board
        image: huijun.azurecr.io/board:BUILDID
        env:
        - name: PROFILE
          value: prod