apiVersion: v1
kind: Namespace
metadata: 
  name: production
---
apiVersion: networking.k8s.io/v1beta1			
kind: Ingress				
metadata:
  name: board	
  namespace: production		
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    
spec:
  rules:
  - host: api.board.com
    http:
      paths: 
      - path: /
        backend:
          serviceName: board-loadbalancer
          servicePort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-dp
  namespace: production	
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: board
  template:
    metadata:
      labels:
        type: app
        service: board
    spec:
      containers:
      - name: board
        image: huijun.azurecr.io/board:v2
        env:
        - name: PROFILE
          value: prod

---
apiVersion: v1
kind: Service
metadata:
  name: board-loadbalancer
  namespace: production	
spec:
  type: LoadBalancer
  ports: 
  - port: 8761
    protocol: TCP
    targetPort: 8080
  selector:
    type: app
    service: board