apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: board
  template:
    metadata:
      labels:
        type: app
        service: board
    spec:
      containers:
        - name: board
          image: huijun.azurecr.io/board:$$(Build.BuildId)
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: profile
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MYSQL_URL.txt
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MYSQL_PORT.txt
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MYSQL_USER.txt
            - name: MYSQL_PW
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MYSQL_PW.txt