version: '2'
services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: 1000kit/h2
    ports:
      - "8181:8181"
      - "1521:1521"
      - "8082:8082"
    volumes:
      - h2-data:/opt/h2-data
  board:
    container_name: board
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - 'h2'
    depends_on:
      - 'h2'
volumes:
  h2-data:
#END