spring:
  datasource:
    url: "jdbc:mysql://board-db.mysql.database.azure.com:3306/board_db?serverTimezone=UTC&characterEncoding=UTF-8"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "huijun@board-db"
    password: "*"
  jpa:
    hibernate:
      format_sql: true
      ddl_auto: create

banner:
  location: "classpath:banner.txt"

loggig:
  level:
    com:
      project:
        board: "DEBUG"
