spring:
  datasource:
    url: "jdbc:h2:~/test"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "sa"

banner:
  location: "calsspath:banner.txt"

loggig:
  level:
    com:
      project:
        board: "DEBUG"
