spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/board_db?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      format_sql: true
      ddl_auto: ${AUTO_DDL}

banner:
  location: "classpath:banner.txt"

hikari:
  pool-name:
    my-dbcp connection-timeout: 10000
    maximum-pool-size: 16
    max-lifetime: 240000
