spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/board_db?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER}
    password: ${MYSQL_PW}
    hikari:
      pool-name:
        idle-timeout: 10000
        vaildation-timeout: 10000
        connection-timeout: 10000
        max-lifetime: 240000
  jpa:
    hibernate:
      format_sql: true
      ddl_auto: ${AUTO_DDL}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: "/WEB-INF/view/"
      suffix: ".jsp"

devtools:
  livereload:
    enabled: true

banner:
  location: "classpath:banner.txt"

